apiVersion: apps/v1
kind: Deployment
metadata:
  name: testservicetwo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testservice2
    template:
      metadata:
        labels:
          app: testservice2
      spec:
        containers:
          -name: testservice2
          image: akshansv/testservice2
